version: 1.1 b{build}
image: Visual Studio 2022
build_script:
- cmd: >-
    dotnet restore --nologo

    dotnet build --nologo -c Release

    dotnet publish --nologo -r win-x64 --no-self-contained -p:PublishSingleFile=true -c Release -o %APPVEYOR_BUILD_FOLDER%/x64 TwitterDump\TwitterDump.csproj

    dotnet publish --nologo -r win-x86 --no-self-contained -p:PublishSingleFile=true -c Release -o %APPVEYOR_BUILD_FOLDER%/x86 TwitterDump\TwitterDump.csproj
artifacts:
- path: x64\TwitterDump.exe
  name: 64-bit executable
- path: x64\TwitterDump.pdb
  name: 64-bit debug symbol database
- path: x86\TwitterDump.exe
  name: 32-bit executable
- path: x86\TwitterDump.pdb
  name: 32-bit debug symbol database
