version: 1.1 b{build}
image: Visual Studio 2022
build_script:
- cmd: >-
    dotnet restore
    dotnet build -c Release
    dotnet pack --include-symbols --include-source -c Release
    dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true -p:PublishTrimmed=true -c Release
    dotnet publish -r win-x86 -p:PublishSingleFile=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true -p:PublishTrimmed=true -c Release
artifacts:
- path: bin\Release\net6.0\win-x64\publish\TwitterDump.exe
  name: 64-bit executable
- path: bin\Release\net6.0\win-x64\publish\TwitterDump.pdb
  name: 64-bit debug symbol database
- path: bin\Release\net6.0\win-x86\publish\TwitterDump.exe
  name: 32-bit executable
- path: bin\Release\net6.0\win-x86\publish\TwitterDump.pdb
  name: 32-bit debug symbol database
