version: 1.0 b{build}
image: Visual Studio 2022
configuration: Release
platform:
- x86
- x64
before_build:
- cmd: nuget restore
build:
  project: TwitterDump.sln
  parallel: true
  verbosity: normal
after_build:
- cmd: 7z a -t7z -ms=on -mqs -slp -bt -bb3 -bsp1 -sae -m0=LZMA2 -mx=9 -myx=9 -md=128m -mfb=273 -mmt=8 -- Windows.%PLATFORM%.%CONFIGURATION%.7z %APPVEYOR_BUILD_FOLDER%\bin\%PLATFORM%\%CONFIGURATION%\net6.0\
artifacts:
- path: Windows.%PLATFORM%.%CONFIGURATION%.7z
